### ISSUE TITLE
Single-session parallel computing on Windows

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#10]
@dkahle suggested [parLapply()](https://stat.ethz.ch/R-manual/R-devel/library/parallel/html/clusterApply.html). Creating the cluster, importing the environment, etc. would require more work and care.

**Comment by dkahle** [comment]
Link that has most of what you need for the implementation (I think): http://adv-r.had.co.nz/Profiling.html#parallelise

**Comment by wlandau-lilly** [comment]
Correction: `parLapply()` will become the default only for Windows. The default for all other systems will remain `mclapply()`, which has less overhead. (In the next open-source disclosure from the company, see `default_parallelism()`, which checks the platform.)

**Comment by wlandau-lilly** [comment]
Fixed (version 2.1.0 is disclosed to GitHub).

**Comment by wlandau-lilly** [comment]
Failing in development R (3.4.0 and 3.5.0). Needed to use `clusterExport()` to export EVERYTHING called from `build()`, including `eply::unquote()`, `%>%`, `tools::md5sum()`, and functions from drake itself. Just made a successful patch, will disclose ASAP.

**Comment by wlandau-lilly** [comment]
Fixed in commit 3daaaf34a3315ffcbc718d72f722029c24a4e970.
