### ISSUE TITLE
Fix spelling of pacakge_dependency_version()

### ISSUE THREAD

**Issue by jarad** [wlandau-lilly/drake#100]
https://github.com/wlandau-lilly/drake/blob/47ca44a62a8a47fab5439797bbdafd86ad88767e/R/package_dependencies.R#L40

**Comment by wlandau-lilly** [comment]
Good catch. As it turned out, there was a lot more [spellchecking](https://github.com/ropensci/spelling) to do too.

Also, you should probably get some sort of prize for submitting the hundredth issue.
