### ISSUE TITLE
Basic example fails with default value of gather in summaries command

### ISSUE THREAD

**Issue by jarad** [wlandau-lilly/drake#101]
The [basic example](https://github.com/wlandau-lilly/drake/blob/master/R/basic_example.R), that is also found in the [quickstart vignette](https://github.com/wlandau-lilly/drake/blob/master/vignettes/quickstart.Rmd), fails if `gather = NULL` is removed from the `summaries` command. This also occurs in the examples for the `summaries()` function (I can't figure out where in the R/ directory this function is, otherwise I would have linked to it), e.g. `check(summaries(summary_types, analyses, datasets))`. 

The error is 

> Error in build_graph(plan = plan, targets = targets, envir = envir, verbose = verbose) : 
>   Workflow is circular (chicken and egg dilemma).

which is caused by the targets `coefs` and `pred` in the basic example and `coef` and `summ` in `summaries()` example.

It is unclear to me (so far) what the gather argument is intended to do, but it seems like poor behavior for the default argument to not work in these simple examples. The comment in both the quickstart and the basic example are that `gather=NULL` only for readability reasons, but it appears that more is going on here.

**Comment by wlandau-lilly** [comment]
`gather()` (optionally called by `summaries()`) creates a new target by combining multiple targets together (via `list()`, `rbind()`, or some other function). These aggregated targets need new names, such as `coef`. I made the mistake of making an aggregated target named `coef` and importing a function also named `coef`. Stay tuned for a bugfix.

**Comment by wlandau-lilly** [comment]
I just changed `coef()` to `coefficients()` in every `*.R` and `*.Rmd` file. I confirmed that that it fixed the errors in `make(load_basic_example())`, the [basic example script](https://github.com/wlandau-lilly/drake/blob/master/R/basic_example.R), the [quickstart vignette](https://github.com/wlandau-lilly/drake/blob/master/vignettes/quickstart.Rmd), and `check(summaries(...))` in the [`summaries()` examples](https://github.com/wlandau-lilly/drake/blob/master/R/generate.R#L214).

This was very helpful of you to point out. Please let me know if you find other rough spots.
