### ISSUE TITLE
Revert #6

### ISSUE THREAD

**Issue by wlandau** [wlandau-lilly/drake#103]
After taking a break and thinking it over, I anticipate serious problems with #6. It makes projects overreactive and brittle, shortening shelf lives and triggering unexpected builds when downloading an old project to another system (similar to richfitz/remake#176, which is otherwise not a problem for drake). I think it would be better to **not** track packages as dependencies, regardless of how a package is fingerprinted.

Packrat is a much more appropriate solution to package reproducibility,  and it **lengthens** project shelf lives. Docker should take care of reproducibility across systems. We should recommend those tools, drake does not excel in that space.

We will need to update the images in the READ ME and vignettes, which will make this repo bigger, but it can't be helped.

**Comment by wlandau** [comment]
@AlexAxthelm if you are still interested in building a tool that detects changes in packages, I think there is still a need. It could enhance packrat, and with the right extensions, maybe even replace it.

**Comment by AlexAxthelm** [comment]
I'll let you know when I come up with something. This is a pretty big deal for, since I know that a lot of my projects will get re-run regularly with new data, but I don't want them to also re-run on spurious package updates.
