### ISSUE TITLE
evaluate() with file targets

### ISSUE THREAD

**Issue by dapperjapper** [wlandau-lilly/drake#106]
`evaluate()` modifies target names by appending an underscore and a given wildcard value. This breaks file targets, where they must end in an extension and a single quote. An example:

```r
drake::plan(
  data = readRDS("data_..datasize...rds")
) %>% 
  rbind(drake::plan(
    file.csv = write.csv(data_..datasize.., "data_..datasize...csv"),
    strings_in_dots = "literals",
    file_targets = T
  )) %>%
  evaluate(rules = list(..datasize.. = c("small", "large")))

            target                                 command
1       data_small               readRDS('data_small.rds')
2       data_large               readRDS('data_large.rds')
3 'file.csv'_small write.csv(data_small, "data_small.csv")
4 'file.csv'_large write.csv(data_large, "data_large.csv")
```

Output should be: 

```r
            target                                 command
1       data_small               readRDS('data_small.rds')
2       data_large               readRDS('data_large.rds')
3 'file_small.csv' write.csv(data_small, "data_small.csv")
4 'file_large.csv' write.csv(data_large, "data_large.csv")
```

**Comment by wlandau-lilly** [comment]
@dapperjapper constructing workflow plans is sometimes not straightforward for large projects. I do not plan to change the behavior of `evaluate()`, but I do plan to improve the documentation on this at the top of the `caution.Rmd` vignette. For more precise control over target names, you might have a look at the [wildcard package](https://github.com/wlandau/wildcard).

**Comment by wlandau** [comment]
For reference: https://ropensci.github.io/drake/articles/caution.html#beware-unparsable-symbols-in-your-workflow-plan-

**Comment by wlandau** [comment]
Update: see the 2018-02-25 edit to https://github.com/ropensci/drake/issues/106#issuecomment-336555049.
