### ISSUE TITLE
Contemplate an rslurm backend

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#120]
Implementation would be similar to the [future_lapply funcionality](https://github.com/wlandau-lilly/drake/blob/master/R/future.R). @kendonB, do the examples in the [rslurm vignette](https://cran.r-project.org/web/packages/rslurm/vignettes/rslurm.html) work for you? This would be the biggest reason for adding or not adding a separate backend. I do not want the `drake` code base to get too large, but I may add a special case if it makes or breaks a project that needs serious HPC.

**Comment by wlandau-lilly** [comment]
@kendonB I am particularly curious about your experience trying out `slurm_apply()`.

**Comment by kendonB** [comment]
It almost works: https://github.com/SESYNC-ci/rslurm/issues/15

**Comment by kendonB** [comment]
Got rslurm to work with the change suggested in SESYNC-ci/rslurm#15!

**Comment by wlandau-lilly** [comment]
Moot now that #115 is solved. `Drake` already has two completely independent ways to use SLURM, and that is plenty. But if someone has a burning desire to build in [rslurm](https://cran.r-project.org/web/packages/rslurm/vignettes/rslurm.html) natively, I might be persuaded, and I will consider pull requests.

**Comment by wlandau-lilly** [comment]
@kendonB I did not mean to sound dismissive of your efforts on `rslurm`. I am really glad you put in the time, and I am glad you have a backup. Nothing was wasted.
