### ISSUE TITLE
Reports of large memory usage for the host process.

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#124]
Continuing from [here](https://github.com/wlandau-lilly/drake/issues/115#issuecomment-340720164) in #115. @kendonB, about how much memory does the host process end up consuming? What does that look like in comparison to the size of the `.drake` cache?.

**Comment by wlandau-lilly** [comment]
@kendonB, I think I fixed the memory issues in 1e5daeded15086d6c2bf2718a18f381999d0a9df. Would you try again?

**Comment by kendonB** [comment]
Seems to have worked perfectly!!

**Comment by wlandau-lilly** [comment]
That's a relief!
