### ISSUE TITLE
normalize the cache path

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#13]
Changing the working directory mid-build can confuse drake.

**Comment by wlandau-lilly** [comment]
Now documented in the [caution vignette](https://github.com/wlandau-lilly/drake/blob/master/vignettes/caution.Rmd).

**Comment by wlandau-lilly** [comment]
Solution:
1. Give the full path to `storr_rds()` instead of just the relative path, `".drake"` (stored in `cachepath`)
1. Use  `config$cache$driver$path` rather than `cachepath` after the cache is already created.

We should test that the user can change the working directory and still have the same results for `config$cache$list()`. Also, we should not forget to remove the mention in the cautoin vignette before closing the issue.

**Comment by wlandau-lilly** [comment]
Edit: use `normalizePath()` to turn a local path into a full path.

```r
normalizePath(".drake")
## [1] "/home/.drake"
```

**Comment by wlandau-lilly** [comment]
After some tinkering, I have found that `normalizePath()` is not enough to solve the issue. However, I still think that `cache$driver$path` should be set to `normalizePath(cache$driver$path)` wherever `cache = storr_rds(...)`. After that, I will probably close this issue. The caution vignette already warns about this, and there is not much else I think can be done.

**Comment by wlandau-lilly** [comment]
Actually, we probably do not need to bother with `normalizePath()` in `drake` because

1. the analogous issue will soon be fixed in `storr`, and
1. users will still not be able to change working directory mid-project anyway.

**Comment by wlandau-lilly** [comment]
I think it will be okay to wait for `storr`.

**Comment by wlandau-lilly** [comment]
Confirmed: [paths are normalized](https://github.com/richfitz/storr/blob/master/R/driver_rds.R#L116) in the  [new storr](https://github.com/richfitz/storr), which is currently in v1.1.2 and apparently [on its way to CRAN](https://cran.r-project.org/web/packages/storr/index.html).

**Comment by AlexAxthelm** [comment]
Will we need to take action to resolve this when that hits CRAN?

**Comment by wlandau-lilly** [comment]
In this case, I do not think there is anything to resolve. We just have a little extra error checking now. Thankfully, doubly-normalized paths are totally fine.

```r
normalizePath(normalizePath("~")) == normalizePath("~")
## TRUE
```
