### ISSUE TITLE
Consider another message for the stage after the first round of ``imports`` and before the second round of ``checks``

### ISSUE THREAD

**Issue by kendonB** [wlandau-lilly/drake#130]
I'm noticing some speed ups since your latest changes. Superb.

However, I still see the messages hang after the first round of ``imports`` and before the second round of ``checks``

For example, I could see ``import slice`` for 70 seconds before ``check 7 items:`` appeared. What happens at this stage?

**Comment by wlandau-lilly** [comment]
Each ["check: ..."](https://github.com/wlandau-lilly/drake/blob/master/R/parallel.R#L21) happens once every [parallelizable stage](https://github.com/wlandau-lilly/drake/blob/master/R/parallel.R#L16), and all the stages happen in [run_parallel()](https://github.com/wlandau-lilly/drake/blob/master/R/parallel.R#L8). If you get a chance to `debug(drake:::parallel_stage); make(your_plan)` on a large project before I do, please let me know. For just imports, you can run `debug(drake:::parallel_stage); make_imports(config(your_plan))`.

**Comment by kendonB** [comment]
In ``next_targets``, the following loop is the culprit:
```
number_dependencies <- sapply(V(graph_remaining_targets),
        function(x) {
            adjacent_vertices(graph_remaining_targets, x, mode = "in") %>%
                unlist() %>% length()
        })
```
I haven't gone deeper than this.

**Comment by wlandau-lilly** [comment]
Ah yes, that makes sense. What if we parallelize it with `lightly_parallelize()`? Would that be enough?

**Comment by kendonB** [comment]
Certainly worth lightly parallelizing if other efficiencies are high development cost.

**Comment by wlandau-lilly** [comment]
I just sped up `next_targets()` in 67db56d598231e15b7e855458e59010d48e15604. When you get a chance, would you try again and tell me whether you still want additional console messages?

**Comment by kendonB** [comment]
That stage went in a flash, However, there is similar behavior befor the next check stage.

```
check 92 items: ...
import ... many
check 7 items: ...
import ... many
import last function slow - something else slow is happening here
check 92 items ...

**Comment by wlandau-lilly** [comment]
Hmm... before or after `next_targets()` in `parallel_stage()`?

**Comment by wlandau-lilly** [comment]
And it's really only one function that's slow to import?

**Comment by wlandau-lilly** [comment]
@kendonB I think I fixed the hang. When I reproduced it on an old project, I found a spot in `outdated()` where things were both slow and silent. Now, they are lightly parallelized and verbose. When you get a chance, please try again on 0dc66e2b7c5932a3de4c8fc045350b17b41438b7 or later.

**Comment by kendonB** [comment]
Looking good at this point. The most time consuming chunks are now the ``check ...``s, as expected. Are those lightly parallelized? I'm reluctant to recommend doing that as I presume this is an I/O heavy stage? 
Regardless, my project checks it's up to date in 2.6 mins now, down from 10 👍 .

**Comment by wlandau-lilly** [comment]
Great to hear! And yes, all the `check`s are lightly parallelized now. Every `check` message is inside a call to [hash_list()](https://github.com/wlandau-lilly/drake/blob/0dc66e2b7c5932a3de4c8fc045350b17b41438b7/R/hash.R#L1). [Rehashing custom external file targets](https://github.com/wlandau-lilly/drake/blob/0dc66e2b7c5932a3de4c8fc045350b17b41438b7/R/hash.R#L72) is probably the heaviest I/O there.

Given the size of your project, it does not surprise me that hashing is the bottleneck. This is pretty much how it should be. `Drake` does try to avoid (re)hashing where possible, even making use of file modification times to check if rehashing is worth the trouble (see #4).

I will close this issue for now. I am willing to reopen it if you think we should tackle more bottlenecks.
