### ISSUE TITLE
Back compatibility and #129

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#134]
#129 will clean up internals and open up more possibilities for future development (#126, #131). But unfortunately, we pretty much give up back compatibility. It seems like the safest way to handle it is to be honest:

```r
make(my_plan)
```

```r
## Error: the project at '~/.drake' was previously built by drake 4.4.0.
## You are running drake 5.0.0, which is not back-compatible.
## To format your cache for the newer drake, try migrate('~/.drake').
## migrate() preserves the statuses of your targets (up to date vs outdated).
## But in case of errors, migrate() first backs up '~/.drake' to  '~/.drake_old'.
```

Does that sound reasonable? Migrating should take about as long as it takes to copy the cache and then load and re-cache all the targets.

**Comment by wlandau-lilly** [comment]
Update: in my [preliminary work](https://github.com/wlandau-lilly/drake/tree/issue129) on #129, I found that non-back-compatible projects just rerun from scratch without a hitch. Clearly, though, there should also be a `migrate()` function so we can avoid having to rebuild targets.

**Comment by dapperjapper** [comment]
Personally, I don't mind having to rebuild targets, as long as it is made clear before one upgrades. I am constantly iterating anyway, so it is not such a major setback. But I'm not sure how other people use drake.

**Comment by wlandau-lilly** [comment]
@dapperjapper that helps to know. Hopefully with `migrate()`, you will not have to, but migration might not be bug-free.

**Comment by wlandau-lilly** [comment]
What about you, @kendonB? I will be busier than usual this weekend and next week, but otherwise, development of #129 is going more easily and smoothly than I expected. I will be sure to let you know if/when I merge a non-back-compatible version to master. I already built in the safety check that prevents `drake` from trampling on a cache with the old format (checks the version of `drake` from `session()`). And next week's CRAN release will be at 0dc66e2b7c5932a3de4c8fc045350b17b41438b7 (back compatible) unless there are any last-minute surprises or requests.

**Comment by kendonB** [comment]
Rebuilding targets is a very minor inconvenience - my drake project runs overnight. I probably would rebuild rather than (nervously) use migrate

**Comment by wlandau-lilly** [comment]
Hmm... and your project is enormous. I will still implement and unit-test `migrate()` just to be safe, but now I wonder if many people will actually use it.

When you do rebuild your targets, you will need to use `make(..., force = TRUE)` the first time. I have not implemented `force` yet, but I will do so before merging with `master`.

**Comment by wlandau-lilly** [comment]
#129 is now fixed.
