### ISSUE TITLE
Consider a user-visible get_connections function?

### ISSUE THREAD

**Issue by kendonB** [wlandau-lilly/drake#143]
I have a large project that requires several calls to ``make`` in order to completely build, as I need to change configuration variables for SLURM for different sets of targets.

It would be nice to be able to somehow recycle the determined connections from the first call to ``make``.

A nice way to achieve this might be a ``get_connections`` function with a ``connections`` argument to ``make``. 

Perhaps a nicer way to achieve this would be to cache at most one set of connections and check the plan data.frame using ``identical``. This one wouldn't require any user visible changes.

**Comment by wlandau-lilly** [comment]
I think we could just recycle the `igraph` object. It's part of `config()`, and it is cached. All I need to do is feed it back into `make()` and suppress `build_graph()` for existing graphs. Does that sound good?

```r
load_basic_example()
config <- config(my_plan)
graph <- config$graph # igraph object with all the connections.
make(my_plan, graph = graph) # Coming soon.
```

**Comment by kendonB** [comment]
Sounds like this will work great!

**Comment by wlandau-lilly** [comment]
Glad we are in agreement. I will try to get it done by the end of the weekend.

**Comment by kendonB** [comment]
You may also want to implement a simple check that would throw an error if ``my_plan`` and ``graph`` are obviously incompatible.

**Comment by wlandau-lilly** [comment]
Sure, if the workflow plan has targets not in the graph.

**Comment by wlandau-lilly** [comment]
Feel free to supply the graph to `make()` now. It is even cached. You can retrieve it with `read_graph()`.

**Comment by kendonB** [comment]
@wlandau-lilly, there still seems to be a slow bit in ``check_config/missing_input_files``:

The loop: ``next_targets(config$graph, jobs = config$jobs)`` takes a long time. Is this work that can be moved out of ``make`` in any way? Recall that the use case builds a subset of targets in each of many calls to ``make``. So I want to move as much work as possible outside of the ``make`` call.

**Comment by wlandau-lilly** [comment]
`next_targets()` does not even belong in `missing_input_files()`! I am surprised I put that there. Will fix as soon as the tests are done.

**Comment by wlandau-lilly** [comment]
Should be fixed in cc5bab9f5166400924353cf515bd12c9ebc0b3d4. See the [new magrittr pipe chain in check.R](https://github.com/wlandau-lilly/drake/blob/master/R/check.R#L67).

**Comment by kendonB** [comment]
@wlandau-lilly ``make`` tries to build all targets when supplying the graph argument. Not quite working as intended yet!

**Comment by wlandau-lilly** [comment]
I see:

```r
load_basic_example()
con <- config(my_plan)
make(my_plan, graph = con$graph, targets = c("small", "large")) # Makes the other targets too.
```

The solution is a mandatory pruning step for the graph: i.e., moving [this code chunk](https://github.com/wlandau-lilly/drake/blob/master/R/graph.R#L103) out of `build_graph()`. That means more time-consuming overhead even when a graph is supplied. A custom `graph` is already advanced, so I think you would be better served by creating a subgraph graph for each separate stage of your workflow.

**Comment by kendonB** [comment]
Does a ``graph`` argument to ``build_graph`` make sense here rather than making a ``prune_graph`` function? If ``graph`` is given, skip the prepruning parts.

**Comment by wlandau-lilly** [comment]
Very well, you have convinced me. As of  de4b76f8195f63adcd4b123ffbf6cc74ef39c496, [drake always prunes the graph](https://github.com/wlandau-lilly/drake/blob/de4b76f8195f63adcd4b123ffbf6cc74ef39c496/R/config.R#L117). I also think I made the pruning code faster in general. But if you find that pruning is too slow, we can always cut it out and instruct users to take advantage of the new optional exported [prune_graph() function](https://github.com/wlandau-lilly/drake/blob/de4b76f8195f63adcd4b123ffbf6cc74ef39c496/R/graph.R#L140).

**Comment by kendonB** [comment]
@wlandau-lilly are you able to lightly parallelize the new function? it runs a lot slower on my 16-core machine :)

**Comment by kendonB** [comment]
Also, build_graph seems to prune even if it is not required, which is unnecessary work

**Comment by kendonB** [comment]
the new function also seems to have become incredibly memory hungry

**Comment by wlandau-lilly** [comment]
I just modified `prune_graph()`. I took some old lightly parallelized code that very recently was at the bottom of `build_graph()`.

**Comment by wlandau-lilly** [comment]
I agree that the graph could be constructed more efficiently. However, I do not think it is as simple as turning off the pruning. Before the nodes are connected, everything in your R workspace is checked for dependencies and treated as a possible import node. So there are usually superfluous import nodes that need to be trimmed away, even if you plan to build all the targets.

**Comment by wlandau-lilly** [comment]
By the way, the previous `prune_graph()` relied on `igraph::make_ego_graph()`, and I am surprised to hear that that was both slow and memory-inefficient. You may want to post an issue on the `igraph` development page.

Also, I just deprecated a bunch of functions as part of my work on #147. The rOpenSci reviewers pay special attention to name conflicts with functions from popular packages, and `drake` needs to adapt. The deprecated functions will remain for several months before I remove them entirely.

**Comment by kendonB** [comment]
@wlandau-lilly ``prune_graph`` seems to be working fast and efficient now. I think I was wrong about the memory efficiency.

However, ``outdated`` and ``make`` now think targets are out of date when they are not. If I specify the ``targets`` argument, these functions correctly see that targets are up to date. However, if I leave the ``targets`` argument out, it incorrectly says that targets are out of date.

**Comment by wlandau-lilly** [comment]
Odd, unit tests still pass. Would you show me with the basic example?

**Comment by kendonB** [comment]
I can't reproduce this with the basic example, sorry. I will keep investigating

**Comment by kendonB** [comment]
My bad. I was finding disagreement between outdated and make by failing to pass the packages argument to outdated. Seems to be working great now!

**Comment by wlandau-lilly** [comment]
What a relief! That’s the most important thing to not break, especially now with #147!
