### ISSUE TITLE
targets built with trigger = "missing" remain out of date

### ISSUE THREAD

**Issue by kendonB** [wlandau-lilly/drake#144]
I thought these would show as up to date.

``` r
library(drake)                    
load_basic_example()              
outdated_1 <- outdated(my_plan)   
make(my_plan, trigger = "missing")
outdated_2 <- outdated(my_plan)   
identical(outdated_1, outdated_2) 
#> [1] TRUE
```

**Comment by kendonB** [comment]
I guess any target built with the ``trigger`` argument will also have the same problem?

**Comment by wlandau-lilly** [comment]
Targets with `missing` or `command` triggers are disconnected from their imported dependencies. This is useful for skipping imports, but it messes with dependency hashes. There are several ways we might adjust, but at the moment, there is just a little message cautioning anyone using non-default triggers that some targets could be out of date.

**Comment by kendonB** [comment]
Is it possible to address this issue in principle? Perhaps creating dependency hashes for only targets that get built?

**Comment by wlandau-lilly** [comment]
I wish that solved it. But unless we have all the dependency hashes stored for `make(..., trigger = "missing")`, there will still be incorrectly outdated targets. `Drake` needs to compare the current dependency hashes to the ones from the previous `make()`, which means the `igraph`s have to agree. I do not know how to skip the right imports without cutting away from the `igraph`.

**Comment by wlandau-lilly** [comment]
When we solve #143, this problem will probably go away when you supply a complete `igraph`. But if you supply an `igraph`, none of your imports will be skipped.

**Comment by wlandau-lilly** [comment]
The simplest thing to do is just never skip any connected imports. Would that be acceptable to you?

**Comment by wlandau-lilly** [comment]
Regardless of how we address this issue, there needs to be documentation in the [caution](https://github.com/wlandau-lilly/drake/blob/master/vignettes/caution.Rmd) and [debug](https://github.com/wlandau-lilly/drake/blob/master/vignettes/debug.Rmd) vignettes.

**Comment by kendonB** [comment]
Not sure what "never skip any connected imports" means exactly.

**Comment by wlandau-lilly** [comment]
If you run `make(my_plan, trigger = "missing")`, none of the imports will be processed. This could save time for workflows with large files or objects to import. Below, the imports are usually printed as they are processed.

```r
> make(my_plan, trigger = "missing")
cache /lrlhps/users/c240390/.drake
connect 26 imports: x, summary_types, analyses, cache, unlisted, gwd, simulat...
connect 15 targets: 'report.md', small, large, regression1_small, regression1...
check 2 items: small, large
target small: trigger "missing"
target large: trigger "missing"
check 4 items: regression1_small, regression1_large, regression2_small, regre...
target regression1_small: trigger "missing"
target regression1_large: trigger "missing"
target regression2_small: trigger "missing"
target regression2_large: trigger "missing"
check 8 items: summ_regression1_small, summ_regression1_large, summ_regressio...
target summ_regression1_small: trigger "missing"
target summ_regression1_large: trigger "missing"
target summ_regression2_small: trigger "missing"
target summ_regression2_large: trigger "missing"
target coef_regression1_small: trigger "missing"
target coef_regression1_large: trigger "missing"
target coef_regression2_small: trigger "missing"
target coef_regression2_large: trigger "missing"
check 1 item: 'report.md'
unload 11 items: regression1_small, regression1_large, regression2_small, reg...
target 'report.md': trigger "missing"
Used non-default triggers. Some targets may be not be up to date.
```

**Comment by kendonB** [comment]
And you can't process only the imports for those targets that are missing?

**Comment by wlandau-lilly** [comment]
As with the other factors behind the decision to build, missingness is checked at the last minute, which is usually after the imports are already processed. Plus, multiple targets usually share the same imports, so removing them is tricky if we do it later.

**Comment by kendonB** [comment]
Ah I see. Perhaps the graph argument to make plus always processing imports is the best solution here then. That would be enough to make ``make`` blast through fast for a small number of missing targets, right?

**Comment by wlandau-lilly** [comment]
Once the imports are processed, the rest should be fast. So you think imports should always be processed? I think that's the easiest thing for everyone to understand, and you wouldn't even need the `graph` argument. My only concern is super large imports, but that does not seem to be very common.

**Comment by kendonB** [comment]
``imports`` are all code, correct? Those go fast always.

**Comment by wlandau-lilly** [comment]
Not always. For example, they could be pre-existing files or large datasets in your workspace that you scrape from the web.

**Comment by kendonB** [comment]
I guess you do want a way to hide large input files from drake. I do it by just referencing the files in code, rather than in commands, which is a bit hacky. A perfect solution to this issue would skip over imports that only feed into targets for which ``trigger = missing``, but a good temporary solution would process all the imports.

**Comment by wlandau-lilly** [comment]
Any of those directions would be progress, but they are still unsatisfying. If we skip any imports, even those only feeding into targets with the `missing` trigger, I think we still run into the same problem.

I am actually leaning towards a different solution: have a separate user-side function that repairs the dependency hashes. It's an extra step in the transition from the `missing` trigger to the the default one, but if we document it, we could have both speed and reproducibility.

**Comment by kendonB** [comment]
Why not stuff that functionality at the end of ``make``? I can't think of a reason a user would want targets to remain out of date.

**Comment by wlandau-lilly** [comment]
At the end of a `make()` with the `missing` trigger, there may be imports missing from the cache, which would mess up the dependency hashes. It's tricky.

**Comment by wlandau-lilly** [comment]
So maybe we really should just cache all the imports by default. The hack could be in the reverse direction: to force `drake` to be just an ordinary job scheduler, supply an `igraph` without the imports.

**Comment by wlandau-lilly** [comment]
Better yet: maybe a `skip_imports` argument.

**Comment by wlandau-lilly** [comment]
@kendonB your original code should work as expected now. Here is what I got.

```r
library(drake)                    
load_basic_example()              
outdated_1 <- outdated(my_plan)   
make(my_plan, trigger = "missing")
outdated_2 <- outdated(my_plan)   
identical(outdated_1, outdated_2) 
##  [1] FALSE
outdated_2
##  character(0)
```

The unit test for this is better now too.

**Comment by wlandau-lilly** [comment]
And for more speed, there is now a `skip_imports` option to `make()`, which is only meant for debugging and testing. The `graph` argument overrides it, so there is still some flexibility if you're good with `igraph`.

**Comment by wlandau-lilly** [comment]
See #153 and https://github.com/wlandau-lilly/drake/issues/131#issuecomment-343801175. `skip_imports` need no longer sacrifice reproducibility as long as the imports are already cached and up to date.
