### ISSUE TITLE
include message when sending jobs up to the cluster with future_lapply

### ISSUE THREAD

**Issue by kendonB** [wlandau-lilly/drake#145]
Right now, I see:

```
check 108 items: ...
```
without a message for when the jobs get submitted.

**Comment by wlandau-lilly** [comment]
I want this too, but it will have to come through [future](https://github.com/HenrikBengtsson/future). Please see HenrikBengtsson/future#171, HenrikBengtsson/future#67, and HenrikBengtsson/future#141.
