### ISSUE TITLE
rescue_cache() slows down clean()

### ISSUE THREAD

**Issue by kendonB** [wlandau-lilly/drake#149]
1) is there a way to get ``clean`` to quickly delete a target? 

2) the slow bit seems to be rescue_cache and the jobs argument doesn't seem to make it through.

**Comment by kendonB** [comment]
``rescue_cache`` also seems to be memory hungry

**Comment by wlandau-lilly** [comment]
Come to think of it, we really do not need `rescue_cache()` there. I just removed it from `clean()` in bde8150dfc3d3952aab8259f995fe88fbaf8bd89. Is `clean()` fast enough now?

**Comment by wlandau-lilly** [comment]
Related: #135.

**Comment by kendonB** [comment]
clean is fast now!

**Comment by wlandau-lilly** [comment]
Glad to hear it!
