### ISSUE TITLE
Skip all checking if trigger = "always"?

### ISSUE THREAD

**Issue by kendonB** [wlandau-lilly/drake#172]
All the loops take less time with trigger = "always", but they still take up a lot of time with a large project.

Is it feasible to literally skip all the pre-building loops with trigger == "always" (as in not specified as a column in my_plan)?

**Comment by wlandau** [comment]
Good question. In general, I do think those pre-building loops are still necessary because they ensure those targets are listed as up to date for the next ordinary  'make()'. But feel free to point out specific  loops if you think otherwise.

**Comment by wlandau-lilly** [comment]
FYI: as of 3ffacbaec5af5b483da0e5963c1a161ef9d4605f, you can use `drake_build()` to just build an individual target. However, if you use it directly this way, you will need to take care of the HPC yourself.

```r
load_basic_example()
config <- load_basic_example()
out <- drake_build(target = "small", config = config)
## target small
out
##            x y
## 1 -2.5334793 0
## 2  0.4647044 1
## 3  2.2450286 1
## 4 -0.9191532 0
## 5 -0.4187669 0
```

**Comment by wlandau-lilly** [comment]
You may need to `loadd("small", deps = TRUE)` to make sure all the dependencies are loaded first, especially if you just called `drake_config()`. (`Drake` unloads targets from your environment first because nothing can be both a target and an import.)

**Comment by wlandau** [comment]
FYI: the [`workers` package](https://github.com/wlandau/workers) will eventually solve the problem you originally raised. Hopefully we can put a `drake`-like interface on it for building up workflows at some point.
