### ISSUE TITLE
FYI: R-devel (>= 2017-11-22) no longer leave zombie processes behind

### ISSUE THREAD

**Issue by HenrikBengtsson** [wlandau-lilly/drake#184]
In https://github.com/wlandau-lilly/drake/blob/master/vignettes/parallelism.Rmd you have a section on 'Zombies'.  FYI, since 2017-11-22 this is no longer the case in R-devel, cf. https://github.com/wch/r-source/commit/eb468006b82d96917db88e2310286b54a27b47b7.

**Comment by wlandau-lilly** [comment]
In https://github.com/wlandau-lilly/drake/commit/9e7a725b9c10ee79575d731da85763bd4f3283fa, I just clarified that those comments pertain to versions of R prior to 3.5.0. Do you think that covers it?

**Comment by HenrikBengtsson** [comment]
Sure, that looks good.

**Comment by wlandau-lilly** [comment]
Great!
