### ISSUE TITLE
DOCS: Forgotten future::plan()

### ISSUE THREAD

**Issue by HenrikBengtsson** [wlandau-lilly/drake#185]
FYI, in https://github.com/wlandau-lilly/drake/blob/master/vignettes/parallelism.Rmd you've forgot `future::plan()`, i.e. instead of
```r
library(future.batchtools)
drake_batchtools_tmpl_file("slurm") # Write batchtools.slurm.tmpl.
batchtools_slurm(template = "batchtools.slurm.tmpl", workers = 16)
make(my_plan, parallelism = "future_lapply")
```
you should use
```r
library(future.batchtools)
drake_batchtools_tmpl_file("slurm") # Write batchtools.slurm.tmpl.
plan(batchtools_slurm, template = "batchtools.slurm.tmpl", workers = 16)
make(my_plan, parallelism = "future_lapply")
```

The README has a similar problem.

**Comment by wlandau-lilly** [comment]
Thanks, Henrik! I really appreciate comments like these. I have also used

```r
future::plan(batchtools_slurm(template = "batchtools.slurm.tmpl", workers = 16))
```

in place of

```r
future::plan(batchtools_slurm, template = "batchtools.slurm.tmpl", workers = 16)
```

I see that you prefer the latter. Is this simply a matter of style, or do they mean different things? At a glance, the former seems to open up nested parallel backends a bit more easily.

**Comment by HenrikBengtsson** [comment]
I'm actually surprised to see that the first form even works; it's not tested and not officially supported.  For instance, the first form may suggest that also `plan(sequential())` and `plan(batchtools_local())` would work, which they don't.

So use the second form.   That is also need for nested specs, e.g.
```r
plan(list(
  sequential,
  tweak(batchtools_slurm, template = "batchtools.slurm.tmpl", workers = 16)
))
```

**Comment by wlandau-lilly** [comment]
I'm glad you cleared that up. Just so I'm clear on the nesting above, are `batchtools_slurm` jobs called within `sequential` jobs? To next the other way, is it okay to begin with `tweak()`?

```r
plan(list(
  tweak(batchtools_slurm, template = "batchtools.slurm.tmpl", workers = 16)
  sequential
))
```

**Comment by HenrikBengtsson** [comment]
Yes, it's ok to begin with `tweak()`, but is really only needed when using nested plans.

Not sure I understand your question on `sequential`, but (as documented), `sequential` is always the default unless specified otherwise - this also means that:
```r
plan(multiprocess)
plan(list(multiprocess))
plan(list(multiprocess, sequential))
plan(list(multiprocess, sequential, sequential))
plan(list(multiprocess, sequential, sequential, sequential))
...
```
all work the same way.

**Comment by wlandau-lilly** [comment]
Great! In that case, I think I just took care of the changes (man pages, vignettes, `drake_example()` files, and `pkgdown` site).
