### ISSUE TITLE
Consider clarifying the role of imports early on in the vignettes

### ISSUE THREAD

**Issue by kendonB** [wlandau-lilly/drake#189]
Here are some quotes from a conversation I had with an RA who is learning drake in the wild.

> what's the difference between the R objects imported and initial input files?

> Aren't we starting from a clean workspace?

> things in my workspace are functions and datasets (which is the same as initial input files?)

> Would reading in dataset be a step in my workflow, or should it be another object imported from my workspace?

**Comment by wlandau-lilly** [comment]
Absolutely! A mention in the README might be nice too, though space is a bit tighter there. Given other incoming feedback, I'm actually thinking about starting an [FAQ wiki](https://github.com/wlandau-lilly/drake/wiki). What do you think?

**Comment by wlandau-lilly** [comment]
I just added explanations to the beginning of the README, `drake.Rmd` vignette, and `quickstart.Rmd` vignette. I think I covered the issues. Please let me know or submit a PR if you'd like more.
