### ISSUE TITLE
Detect knitr documents knitted with rmarkdown::render()

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#190]
From @AlexAxthelm. Many people prefer `rmarkdown::render()` for knitting R Markdown files, etc. rather than `knitr::knit()`. In that case,

```r
load_basic_example()
my_plan[1, ]

##              target                          command
## 1       'report.md' knit('report.Rmd', quiet = TRUE)
```

would become

```r
##              target                          command
## 1       'report.md' rmarkdown::render('report.Rmd', quiet = TRUE)
```

Just as with `knit()`, we should tweak `drake` to detect calls to `render()`, find `report.Rmd`, and scan active code chunks for dependencies.

**Comment by AlexAxthelm** [comment]
Now that I know where to look, I can try to PR this. It’s a good fit for my next steps at work, so I can spend some time trying to make this extension.

--
Alex Axthelm

On January 16, 2018 at 7:55:29 PM, Will Landau (notifications@github.com<mailto:notifications@github.com>) wrote:

**** This is an EXTERNAL email. Exercise caution. DO NOT open attachments or click links from unknown senders or unexpected email. ****
________________________________

From @AlexAxthelm<https://github.com/alexaxthelm>. Many people prefer rmarkdown::render() for knitting R Markdown files, etc. rather than knitr::knit(). In that case,

load_basic_example()
my_plan[1, ]

##              target                          command
## 1       'report.md' knit('report.Rmd', quiet = TRUE)

would become

##              target                          command
## 1       'report.md' rmarkdown::render('report.Rmd', quiet = TRUE)

Just as with knit(), we should tweak drake to detect calls to render(), find report.Rmd, and scan active code chunks for dependencies.

**Comment by wlandau-lilly** [comment]
The key piece is here: https://github.com/wlandau-lilly/drake/blob/e2bfe946661a102e1f0702c618c09e5848602fad/R/knitr.R#L61

It should change to something like:

```r
does_knitting <-
  is_function_call(expr, package = "knitr", what = "knit") ||
  is_function_call(expr, package = "rmarkdown", what = "render")
if (does_knitting){
```

And `is_function_call()` should accept `"rmarkdown"` and `"render"` as arguments. From a Google search, `rmarkdown` is by far the dominant package with an exported `render()` function, so it will be safe to assume that a call to `render()` in a command is calling the `render()` from `rmarkdown`. Most of the work on this issue will be updating the [unit tests](https://github.com/wlandau-lilly/drake/blob/e2bfe946661a102e1f0702c618c09e5848602fad/tests/testthat/test-knitr.R) and docs.

**Comment by wlandau-lilly** [comment]
And conveniently, both `knitr::knit()` and `rmarkdown::render()` both begin with an argument named `input` (the only relevant argument here), so parsing commands will be the same.

**Comment by AlexAxthelm** [comment]
Maybe looking for render with a file dependency?

--
Alex Axthelm

On January 16, 2018 at 8:23:42 PM, Will Landau (notifications@github.com<mailto:notifications@github.com>) wrote:

**** This is an EXTERNAL email. Exercise caution. DO NOT open attachments or click links from unknown senders or unexpected email. ****
________________________________

The key piece is here: https://github.com/wlandau-lilly/drake/blob/e2bfe946661a102e1f0702c618c09e5848602fad/R/knitr.R#L61

It should change to something like:

does_knitting <-
  is_function_call(expr, package = "knitr", what = "knit") ||
  is_function_call(expr, package = "rmarkdown", what = "render")
if (does_knitting){

And is_function_call() should accept "rmarkdown" and "render" as arguments. From a Google search, rmarkdown is by far the dominant package with an exported render() function, so it will be safe to assume that a call to render() in a command is calling the render() from rmarkdown. Most of the work on this issue will be updating the unit tests<https://github.com/wlandau-lilly/drake/blob/e2bfe946661a102e1f0702c618c09e5848602fad/tests/testthat/test-knitr.R> and docs.

**Comment by wlandau-lilly** [comment]
I'm glad you brought that up. I'm a little hesitant about requiring a detected file dependency because there are calls to `deparse()` in `knitr.R`, which changes single quotes to double quotes. I think we're covered because `drake` looks for an `input` argument.

```r
> deps("knit(not_found, quiet = TRUE)")
Warning: dynamic report 'not_found' does not exist and cannot be inspected for dependencies.
[1] "knit"      "not_found"
> deps("knit(input = not_found, quiet = TRUE)")
Warning: dynamic report 'not_found' does not exist and cannot be inspected for dependencies.
[1] "knit"      "not_found"
>
```

Incidentally, we might also want to fix this warning from [doc_of_function_call()](https://github.com/wlandau-lilly/drake/blob/e2bfe946661a102e1f0702c618c09e5848602fad/R/knitr.R#L76):

```r
> deps("knit(quiet = TRUE)") # The input argument is not set.
Warning in min(which(!nchar(names(args)))) :
  no non-missing arguments to min; returning Inf
[1] "knit"
>
```

**Comment by wlandau-lilly** [comment]
Hmm... on second thought, maybe the `input` arg doesn't disambiguate it enough: `doc_of_function_call()` looks for the first unnamed arg if it can't find an explicit mention of `input`. But I think we're okay since `rmarkdown`'s render is very dominant.

**Comment by wlandau-lilly** [comment]
@AlexAxthelm I REALLY appreciate your offer to do a PR, but I just pushed a fix. Now, you should be able to use `render()` just like `knit()` in your workflow plan commands, and you won't have to go through hundreds of intermediate `*.md` files.

**Comment by wlandau-lilly** [comment]
On an unrelated note, here's where to look for info about triggers:

- https://wlandau-lilly.github.io/drake/articles/debug.html#test-with-triggers-
- https://wlandau-lilly.github.io/drake/articles/example-packages.html

**Comment by AlexAxthelm** [comment]
Works great for me. Thanks. This is so much easier than any of the several workarounds I had tried.

**Comment by wlandau-lilly** [comment]
So glad to hear it!
