### ISSUE TITLE
User-side function to load all the dependencies of a target.

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#20]

**Comment by wlandau-lilly** [comment]
I'm thinking of a function called `load_dependencies(target)` that loads just the dependencies into the user's workspace. It seems as simple as loading the graph from the cache and calling `loadd(dependencies(...))`.

**Comment by wlandau-lilly** [comment]
With `deps()`, this is super easy.

```r
load_basic_example()
make(my_plan)
loadd(deps(my_plan$command[1]))
```

At this point, I do not think it is worth the extra code and docs it would take to build such a small feature into the package. Will reconsider if users want it.

**Comment by wlandau-lilly** [comment]
In b63bfd4b11dbf5cb65bcd9ed79bdd1ccbaa5c7bb, I added a `deps` flag to `loadd()`. That way, you can choose load the dependencies of the targets rather than the targets themselves. This will be useful if you know a target failed and you want to debug in an interactive session. @kendonB, as one of `drake`'s most powerful power users, you might appreciate this.

One caveat: the `deps` flag requires that a 'drake_config()' list is already in the cache, so you need to have called 'make()' first.

**Comment by wlandau-lilly** [comment]
Glad you like it! To read the config object, there is `read_drake_config()` (see also `read_drake_plan()` and `read_drake_graph()`). Good call about `meta_list`. I just implemented and pushed `read_drake_meta()` and documented it in the `debug` vignette. The metadata used for `should_build_target()` is cached in `make()`, and functions like `outdated()` should not modify it.

To avoid race conditions, I needed to store the metadata for each target separately, which exacerbates #154. But I added a new `purge` argument to `clean()`, which should help.

**Comment by kendonB** [comment]
Why does outdated not modify the metadata in should_build_target?

**Comment by wlandau-lilly** [comment]
The saved metadata is for debugging purposes only, and people who debug will probably also use `outdated()`. I do not want the act of debugging to change the recorded results from `make()`, which could take several hours or days to recompute.
