### ISSUE TITLE
Hybrid parallel computing options

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#28]
In `make()`, the `parallelism` argument can be "mclapply" (current default on non-Windows systems), "parLapply" (current default on Windows), or "Makefile". The first two parallelize within a single R session across multiple cores, and the third parallelizes over multiple R sessions and potentially multiple nodes on a cluster. What if we want both kinds of parallelism? The best high-performance computing solutions often have parallelism both among nodes and among cores within nodes. I wonder how to tell drake to partition the targets, use "Makefile" to parallelize among groups, and use one of the other options to parallelize within groups. Maybe `parallel_stage()` can handle it somehow.

**Comment by wlandau-lilly** [comment]
`plot_graph()` now arranges the targets in parallelizable stages (except for the bug in #55). I suppose these stages might use different modes of parallelism if we exclude `Makefile`s. Otherwise, I am not sure it is possible to implement this without seriously re-architecting drake. I have not had any new ideas on this one for several months. This issue may have exhausted its shelf life.

**Comment by wlandau-lilly** [comment]
My best advice is to use `"Makefile"` parallelism and then do your own custom multicore/multithread parallelism within each target. Power users who require this kind of parallelism would probably already know how to do this, and I think it is good enough. Will reopen on request.

**Comment by wlandau-lilly** [comment]
If we use [sparklyr::spark_apply()](https://spark.rstudio.com/) as part of #77, this may come into play. Spark is apparently not designed for general parallelism tasks, it is more about parallelism when you're splitting up a large data file.

**Comment by wlandau** [comment]
From [a comment](https://github.com/wlandau-lilly/drake/issues/42#issuecomment-338310377) by @HenrikBengtsson, nested parallelism might be possible via the `future` package and #42. If #42 succeeds, I will write about it in the parallelism vignette.

**Comment by wlandau-lilly** [comment]
From a comment by @HenrikBengtsson, nested parallelism might be possible via the future package and #42. If #42 succeeds, I will write about it in the parallelism vignette.

**Comment by wlandau-lilly** [comment]
Now documented in the `"future_lapply"` subsection of the [parallelism vignette](https://github.com/wlandau-lilly/drake/blob/master/vignettes/parallelism.Rmd).
