### ISSUE TITLE
rmarkdown should be in Imports and not Suggests?

### ISSUE THREAD

**Issue by vlulla** [wlandau-lilly/drake#32]
I get the error "Error in library(rmarkdown) : there is no package called 'rmarkdown'".  Why is this failing on a suggested package?  Maybe rmarkdown package should be in Imports?

**Comment by wlandau-lilly** [comment]
Are you trying the code from `example_drake("basic")`? Does installing `rmarkdown` or commenting out `library(rmarkdown)` fix the issue for you? If so, this will be fixed along with #29. I will also comment out  `library(rmarkdown)` in `inst/examples/basic/basic.R`.

**Comment by wlandau-lilly** [comment]
I was originally using `rmarkdown` in that example, but I have since commented out that little bit of functionality. `rmarkdown` should really be optional now.

**Comment by wlandau-lilly** [comment]
Verified: in the next patch, you will only need `rmarkdown` to build the vignettes when you install `drake`.

**Comment by vlulla** [comment]
Yes, I tried the example_drake('basic') and that's where I had the problem.  I installed rmarkdown and it solved the issue.  Thanks for looking into this.

**Comment by wlandau-lilly** [comment]
Glad to hear it! Please continue to keep me posted.
