### ISSUE TITLE
Visualize build times

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#57]
Thanks to @dapperjapper, we now have `build_times()` for targets, and @dkahle suggested visualizing them. Whether we weave the built times into `plot_graph()` or create a totally new graph, I do not know.

**Comment by wlandau-lilly** [comment]
After thinking it over, I would really like to put build times directly into the existing graph via `dataframes_graph()`. It would be easy to add a second line in the label for each node with the cached build time, if available. The graph would look something like this.

```r
nodes = data.frame(id = c("x", "y"), label = c("x\n2 minutes", "y\n4 minutes"), color = "#228b22")
edges = data.frame(from = "x", to = "y", arrows = "to")
visNetwork::visNetwork(nodes = nodes, edges = edges)
```

![graph](https://user-images.githubusercontent.com/22958003/29224035-ab2468e2-7e96-11e7-8b58-6c820eb313cb.png)

I suppose we could make the nodes larger or smaller based on build time, but it would be complicated, and I do not think we need to do more than simply list the times.

**Comment by wlandau-lilly** [comment]
And the times should probably be user + system time. Elapsed time does not mean much in many parallel computing workflows.

**Comment by wlandau-lilly** [comment]
On second thought, the visualized times should be elapsed times. For my own large workflows, which I deploy to a cluster and offload to compiled code, the user and system times from `system.time()`  are not representative.

**Comment by wlandau-lilly** [comment]
Done.

**Comment by AlexAxthelm** [comment]
Very excited about this feature.

**Comment by wlandau-lilly** [comment]
So am I. It has been super helpful for my projects at work.
