### ISSUE TITLE
A few fixes to #52

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#62]
Related to @dapperjapper's PR: #52.

1. Add `require("methods", quietly = TRUE)` to the beginning of `build_times()`. For `parallelism = "parLapply"` on Red Hat Linux, `build_times()` quits in error at with a call to `dseconds()`. Apparently, `methods` isn't always loaded because it takes time.
1. Add `methods` to the `Suggests` field in the [DESCRIPTION](https://github.com/wlandau-lilly/drake/blob/master/DESCRIPTION).
1. Add curly braces to an the if-else block in `build()` that records the times.

```r
build = function(...){
  ...
  if(imported){
    value = imported_target(...)
  } else {
    time = system.time({...})
    config$cache$set(..., namespace = "build_times")
  }
  ...
}
```

**Comment by wlandau-lilly** [comment]
Also, I would add the cache as an argument to `build_times()`. This could speed up #57, where `build_times()` is called within `dataframes_graph()`.

```r
build_times = function(path = getwd(), search = TRUE, digits = 0, cache = drake::get_cache(path = path, search = search)){
  ...
}
```

**Comment by wlandau-lilly** [comment]
... though `get_cache()` would have to be exported.

**Comment by AlexAxthelm** [comment]
If you don't want to export `get_cache()` you could use cache as an optional argument:

```r
if (missing(cache) || is.null(cache)){
  cache <- get_cache(path = path, search = search)
}
```

**Comment by wlandau-lilly** [comment]
Looks cleaner than what I have (related: #40). In several places, I export functions just to give reasonable default arguments. Then again, the existing approach gives a little more user-side control. May or may not be worth the time to fix.
