### ISSUE TITLE
Predict the runtime of the next call to make().

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#64]
Sketch:

```r
predict_runtime <- function(plan, parallelism, jobs, ...){
  # What to we need to build?
  run_these <- outdated(plan = plan, ...)

  # How long did those targets take before?
  times <- build_times()[run_these,] # Need to deal with brand new targets somehow.

  # What kind of parallelism do we have?
  nodes <- dataframes_graph(plan = plan, parallelism = parallelism, jobs = jobs, ...)
  
  # Account for targets not yet timed.
  # Account for parallelism.
  # Return estimated total runtime.
}
```

@dapperjapper, back to our conversation from #52, this could a reason to record all the times, not just build times. I am not sure.

**Comment by dapperjapper** [comment]
Looks cool! I can't work on it over the next 2 weeks, but it's a good idea.

**Comment by wlandau-lilly** [comment]
Fixed. See [predict_runtime()](https://github.com/wlandau-lilly/drake/blob/0444b8f4a3813330e0c4cbb63e648e810c03b0aa/R/predict_runtime.R#L63), [rate_limiting_times()](https://github.com/wlandau-lilly/drake/blob/0444b8f4a3813330e0c4cbb63e648e810c03b0aa/R/predict_runtime.R#L187), and the new [timing vignette](https://github.com/wlandau-lilly/drake/blob/master/vignettes/timing.Rmd).
