### ISSUE TITLE
Custom RStudio completers for loadd() and readd()

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#75]
Analogous to richfitz/remake#168.

**Comment by wlandau-lilly** [comment]
As mentioned by @krlmlr and by @kevinushey at [RStudio Support](https://support.rstudio.com/hc/en-us/community/posts/115006099887-remake-fetch-auto-completion?page=1#community_comment_115005321748), we need custom completion first. Will reopen when this functionality is available in RStudio.

**Comment by wlandau** [comment]
I expect slowness because there may be a lot of targets in the cache. `cached()` lists the target names. Will revisit on request.
