### ISSUE TITLE
Get rid of dclean()

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#85]
With #74 solved, we can shave off some testing time.

**Comment by AlexAxthelm** [comment]
If this isn't a huge priority, I can work on this when I move to tests on #40.

**Comment by wlandau-lilly** [comment]
That would be a huge favor, thank you.

**Comment by wlandau-lilly** [comment]
Fixed in a767a35d369b2708c20a8447b2a56baf4c636ae1
